import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'chatter-model-access-'));
process.env.API_DB_PATH = path.join(dir, 'test.sqlite');
process.env.ENCRYPTION_KEY = 'test-model-access-only';
for (const key of ['TIMEWEB_API_KEY', 'TIMEWEB_LITE_API_KEY', 'TIMEWEB_VISION_API_KEY', 'TIMEWEB_LITE_VISION_API_KEY', 'TIMEWEB_PRO_ENDPOINTS', 'TIMEWEB_LITE_ENDPOINTS', 'MODELS_MANUAL']) process.env[key] = '';
const requests: any[] = [];
const server = http.createServer(async (req, res) => {
  let data = ''; for await (const chunk of req) data += chunk;
  const body = JSON.parse(data); requests.push(body);
  if (body.stream) {
    res.writeHead(200, { 'Content-Type': 'text/event-stream' });
    res.end('data: ' + JSON.stringify({ choices: [{ index: 0, delta: { role: 'assistant', content: 'Allowed reply' }, finish_reason: null }] }) + '\n\ndata: ' + JSON.stringify({ choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: { prompt_tokens: 1, completion_tokens: 2, total_tokens: 3 } }) + '\n\ndata: [DONE]\n\n');
  } else res.end(JSON.stringify({ choices: [{ message: { role: 'assistant', content: 'Allowed reply' }, finish_reason: 'stop' }], usage: { prompt_tokens: 1, completion_tokens: 2, total_tokens: 3 } }));
});
await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
const baseUrl = 'http://127.0.0.1:' + (server.address() as any).port + '/v1';
const { db } = await import('../src/db.js');
const settings = await import('../src/services/model-settings.js');
const access = await import('../src/services/model-access.js');
const intervals: ReturnType<typeof setInterval>[] = [];
const realInterval = globalThis.setInterval;
globalThis.setInterval = ((...args: any[]) => { const timer = (realInterval as any)(...args); intervals.push(timer); return timer; }) as typeof setInterval;
const ai = await import('../src/services/ai.js'); globalThis.setInterval = realInterval;
try {
  db.prepare("INSERT INTO users (id, name, status, is_admin) VALUES (1, 'Admin allowed', 'approved', 1), (2, 'Admin denied', 'approved', 1), (3, 'User allowed', 'approved', 0)").run();
  const apiKeyId = settings.importModelKey('Test', 'fake-access-key');
  const model = { id: 'restricted', uniqueId: 'restricted', model: 'restricted-model', baseUrl, apiKeyId, accessMode: 'selected', allowedUserIds: [1], supportsTools: false };
  const publicModel = { ...model, id: 'public', uniqueId: 'public', model: 'public-model', accessMode: 'all', allowedUserIds: [] };
  settings.updateModelSettings({ proModels: [model, publicModel], liteModels: [publicModel], manualModels: [model], visionModel: { id: 'vision', uniqueId: 'vision', baseUrl: '', model: '', apiKeyId: null } });
  ai.refreshConfiguredModels();
  assert.equal(ai.getModelsCatalog(true, 2).length, 0, 'admin cannot bypass a selected-user list');
  assert.equal(ai.getModelsCatalog(true, 1).length, 1);
  assert.equal(ai.resolveManualModel('restricted', true, 2), undefined);
  assert.equal(ai.resolveManualModel('restricted', true, 1)?.id, 'restricted');
  const actor1 = { userId: 1, isAdmin: true }, actor2 = { userId: 2, isAdmin: true }, actor3 = { userId: 3, isAdmin: false };
  const payload = { messages: [{ role: 'user', content: 'Test' }] };
  await access.withModelActor(actor2, () => ai.runCompletion('pro', payload));
  assert.equal(requests.at(-1).model, 'public-model', 'auto fallback skips inaccessible model without requesting it');
  const manual = ai.resolveManualModel('restricted', true, 1)!;
  const before = requests.length;
  await assert.rejects(access.withModelActor(actor2, () => ai.runCompletion('pro', payload, manual)), /model_access_denied/);
  assert.equal(requests.length, before);
  await access.withModelActor(actor1, () => ai.runCompletion('pro', payload, manual));
  assert.equal(requests.at(-1).model, 'restricted-model');
  settings.updateModelSettings({ proModels: [{ ...model, allowedUserIds: [] }], manualModels: [{ ...model, allowedUserIds: [] }] }); ai.refreshConfiguredModels();
  assert.equal(ai.getModelsCatalog(true, 1).length, 0);
  assert.equal(access.canUseModel('restricted', actor1), false);
  await assert.rejects(access.withModelActor(actor1, () => ai.runCompletion('pro', payload)));
  settings.updateModelSettings({ proModels: [{ ...model, accessMode: 'admins', allowedUserIds: [] }], manualModels: [{ ...model, accessMode: 'admins', allowedUserIds: [] }] }); ai.refreshConfiguredModels();
  assert.equal(access.canUseModel('restricted', actor2), true);
  assert.equal(access.canUseModel('restricted', actor3), false);
  settings.updateModelSettings({ proModels: [publicModel], manualModels: [{ ...model, allowedUserIds: [3] }] }); ai.refreshConfiguredModels();
  assert.equal(ai.getModelsCatalog(false, 3).length, 1, 'a selected non-admin is allowed');
  assert.equal(ai.getModelsCatalog(true, 1).length, 0);
  const chatId = Number(db.prepare("INSERT INTO user_chats (user_id, title, room_enabled) VALUES (1, 'Access room', 1)").run().lastInsertRowid);
  db.prepare('INSERT INTO chat_members (chat_id, user_id) VALUES (?, 3)').run(chatId);
  await ai.sendMessageThroughAi(1, 'Room request', chatId, { preferredModel: 'restricted', forcePro: true, initiatorUserId: 3, skipHistory: true, skipUserHistory: true, countAsUserMessage: false });
  assert.equal(requests.at(-1).model, 'restricted-model', 'room access belongs to initiator, not bot owner');
  await assert.rejects(ai.sendMessageThroughAi(1, 'Owner denied', chatId, { preferredModel: 'restricted', forcePro: true, skipHistory: true, skipUserHistory: true, countAsUserMessage: false }), /model_access_denied/);
  assert.throws(() => settings.updateModelSettings({ manualModels: [{ ...model, accessMode: 'invalid' }] }), /invalid_model_access_mode/);
  assert.throws(() => settings.updateModelSettings({ manualModels: [{ ...model, allowedUserIds: ['3'] }] }), /invalid_model_allowed_users/);
  const { exportModelConfig } = await import('../src/services/model-config-transfer.js');
  assert.deepEqual(exportModelConfig(false).models.find(item => item.uniqueId === 'restricted')?.allowedUserIds, [3]);
  console.log('Model access runtime and room tests passed');
} finally { for (const timer of intervals) clearInterval(timer); await new Promise<void>(resolve => server.close(() => resolve())); db.close(); fs.rmSync(dir, { recursive: true, force: true }); }
