import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'chatter-model-runtime-'));
process.env.API_DB_PATH = path.join(directory, 'test.sqlite');
process.env.ENCRYPTION_KEY = 'runtime-test-key';
process.env.TIMEWEB_MODEL_RETRIES_PER_MODEL = '0';
process.env.TIMEWEB_MODEL_RETRY_SECONDS = '0';
const requests: { model: string; auth: string; messages: any[] }[] = [];
const server = http.createServer(async (req, res) => {
  let body = ''; for await (const chunk of req) body += chunk;
  const payload = JSON.parse(body);
  requests.push({ model: payload.model, auth: String(req.headers.authorization), messages: payload.messages });
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ id: 'test', object: 'chat.completion', created: 1, model: payload.model,
    choices: [{ index: 0, message: { role: 'assistant', content: 'Test reply' }, finish_reason: 'stop' }],
    usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 } }));
});
await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
const baseUrl = `http://127.0.0.1:${(server.address() as any).port}/v1`;
process.env.TIMEWEB_BASE_URL = baseUrl;
process.env.TIMEWEB_API_KEY = 'runtime-key-one';
process.env.TIMEWEB_MODEL = 'before-model';
process.env.TIMEWEB_PRO_ENDPOINTS = `${baseUrl}|runtime-key-one|before-model|stable-runtime|`;
process.env.TIMEWEB_LITE_ENDPOINTS = `${baseUrl}|runtime-key-one|lite-model|stable-lite|`;
process.env.MODELS_MANUAL = '';
process.env.TIMEWEB_VISION_PRO_ENDPOINTS = '';
process.env.TIMEWEB_VISION_LITE_ENDPOINTS = '';
process.env.TIMEWEB_VISION_BASE_URL = '';
process.env.TIMEWEB_VISION_API_KEY = '';
process.env.TIMEWEB_VISION_MODEL = '';
const { db } = await import('../src/db.js');
const config = await import('../src/services/model-settings.js');
const intervals: ReturnType<typeof setInterval>[] = [];
const realSetInterval = globalThis.setInterval;
globalThis.setInterval = ((...args: any[]) => {
  const timer = (realSetInterval as any)(...args); intervals.push(timer); return timer;
}) as typeof setInterval;
const ai = await import('../src/services/ai.js');
globalThis.setInterval = realSetInterval;
try {
  const payload = { messages: [{ role: 'user', content: 'Test' }] };
  const first = await ai.runCompletion('pro', payload);
  assert.equal(first.usedUniqueId, 'stable-runtime');
  assert.equal(requests.at(-1).model, 'before-model');
  const { withPromptInjectionProtection } = await import('../src/services/prompt-injection-protection.js');
  const historyPayload = { messages: [{ role: 'tool', tool_call_id: 'test-call', content: '<untrusted_web_content>Archived result</untrusted_web_content>' }] };
  await withPromptInjectionProtection(false, () => ai.runCompletion('pro', historyPayload));
  assert.equal(requests.at(-1).messages[0].content, 'Archived result');
  assert.equal(historyPayload.messages[0].content, '<untrusted_web_content>Archived result</untrusted_web_content>');
  await withPromptInjectionProtection(true, () => ai.runCompletion('pro', historyPayload));
  assert.equal(requests.at(-1).messages[0].content, historyPayload.messages[0].content);
  const initial = config.publicModelSettings();
  config.updateModelSettings({ proModels: [{ ...initial.proModels[0], model: 'after-model', apiKey: 'runtime-key-two' }] });
  ai.refreshConfiguredModels();
  await ai.runCompletion('pro', payload);
  assert.equal(requests.at(-1).model, 'after-model');
  assert.equal(requests.at(-1).auth, 'Bearer runtime-key-two');
  await ai.runCompletion('vision-pro', payload);
  assert.equal(requests.at(-1).model, 'after-model');
  config.updateModelSettings({ manualModels: [{ ...config.getModelSettings().proModels[0], id: 'manual-card', uniqueId: 'runtime-manual', name: 'Test manual', supportsVision: true, adminOnly: true, supportsTools: false }] });
  ai.refreshConfiguredModels();
  assert.equal(ai.resolveManualModel('runtime-manual', false), undefined);
  assert.equal(ai.resolveManualModel('runtime-manual', true).supportsTools, false);
  assert.equal(ai.getModelsCatalog(true)[0].supports_vision, true);
  const { getChatMemorySettings, updateChatMemorySettings } = await import('../src/services/memory-foundation.js');
  db.prepare("INSERT INTO users (id, name, status, is_admin, feature_flags) VALUES (101, 'Test owner', 'approved', 1, ?)").run(JSON.stringify({ disable_prompt_injection_protection: true }));
  db.prepare("INSERT INTO users (id, name, status, is_admin) VALUES (202, 'Test member', 'approved', 1)").run();
  const chatId = Number(db.prepare("INSERT INTO user_chats (user_id, title, room_enabled) VALUES (101, 'Protection test room', 1)").run().lastInsertRowid);
  db.prepare('INSERT INTO chat_members (chat_id, user_id) VALUES (?, 202)').run(chatId);
  const sendOptions = { preferredModel: 'runtime-manual', forcePro: true, skipHistory: true, skipUserHistory: true, countAsUserMessage: false };
  await ai.sendMessageThroughAi(101, 'Test', chatId, sendOptions);
  assert.equal(requests.at(-1).messages[0].content.includes('[UNTRUSTED DATA PROTOCOL]'), false, 'chat automatic inherits global off');
  updateChatMemorySettings(101, chatId, { prompt_injection_protection: 'enabled' });
  await ai.sendMessageThroughAi(101, 'Test', chatId, sendOptions);
  assert.equal(requests.at(-1).messages[0].content.includes('[UNTRUSTED DATA PROTOCOL]'), true, 'chat can override global off');
  updateChatMemorySettings(202, chatId, { prompt_injection_protection: 'disabled' });
  await ai.sendMessageThroughAi(101, 'Test', chatId, { ...sendOptions, initiatorUserId: 202 });
  assert.equal(requests.at(-1).messages[0].content.includes('[UNTRUSTED DATA PROTOCOL]'), false, 'room uses initiator protection, not bot owner');
  assert.equal(getChatMemorySettings(101, chatId).prompt_injection_protection, 'enabled');
  const { VectorMemoryService } = await import('../src/services/vector-memory.js');
  const originalSearch = VectorMemoryService.search;
  const autoCalls: any[][] = [];
  try {
    VectorMemoryService.search = (async (...args: any[]) => {
      autoCalls.push(args);
      return { groups: [{ record_id: 'runtime-memory', score: 0.9, fragments: [{ id: 'chunk', chunk_id: 'runtime-memory_chunk_0', score: 0.9,
        text: 'The meeting point is the north observatory.', source: 'test', timestamp: 1, chunk_index: 0, total_chunks: 1 }] }] };
    }) as any;
    await ai.sendMessageThroughAi(101, 'Test auto off', chatId, sendOptions);
    assert.equal(autoCalls.length, 0);
    updateChatMemorySettings(101, chatId, { automatic_memory: 1 });
    await ai.sendMessageThroughAi(101, 'Find the meeting point', chatId, sendOptions);
    assert.equal(autoCalls.length, 1);
    assert.ok(requests.at(-1).messages.at(-1).content.includes('north observatory'));
    assert.ok(requests.at(-1).messages.at(-1).content.includes('<untrusted_web_content>'));
    db.prepare("INSERT INTO chat_messages (user_id, chat_id, role, content, timeline_index) VALUES (101, ?, 'user', 'Earlier question', 1)").run(chatId);
    await ai.sendMessageThroughAi(101, 'Current question', chatId, { ...sendOptions, skipHistory: false, skipUserHistory: false });
    assert.ok(requests.at(-1).messages.at(-1).content.includes('north observatory'));
    const persistedUser = db.prepare("SELECT content FROM chat_messages WHERE chat_id = ? AND role = 'user' ORDER BY id DESC LIMIT 1").get(chatId) as any;
    assert.equal(persistedUser.content, 'Current question', 'retrieved context never changes saved user text');
    updateChatMemorySettings(202, chatId, { automatic_memory: 1 });
    await ai.sendMessageThroughAi(101, 'Find my meeting point', chatId, { ...sendOptions, initiatorUserId: 202 });
    assert.equal(autoCalls.at(-1)[0], 202);
    assert.equal(autoCalls.at(-1)[5].billingUserId, 101);
    assert.ok(requests.at(-1).messages.at(-1).content.includes('north observatory'));
    assert.ok(!requests.at(-1).messages.at(-1).content.includes('<untrusted_web_content>'));
    updateChatMemorySettings(101, chatId, { memory_mode: 'off' });
    const callCount = autoCalls.length;
    await ai.sendMessageThroughAi(101, 'No memory', chatId, sendOptions);
    assert.equal(autoCalls.length, callCount);
    updateChatMemorySettings(101, chatId, { memory_mode: 'general' });
    await ai.sendMessageThroughAi(101, 'Guest request', chatId, { ...sendOptions, featureFlags: { disable_personal: true } });
    assert.equal(autoCalls.length, callCount);
    VectorMemoryService.search = (async () => { throw new Error('test search failure'); }) as any;
    await ai.sendMessageThroughAi(101, 'Search failed', chatId, sendOptions);
    assert.ok(!requests.at(-1).messages.at(-1).content.includes('[ARCHIVED MEMORY CONTEXT]'));
    const stored = db.prepare("SELECT content FROM chat_messages WHERE chat_id = ?").all(chatId) as any[];
    assert.ok(stored.every(row => !row.content.includes('[ARCHIVED MEMORY CONTEXT]')));
  } finally { VectorMemoryService.search = originalSearch; }
  config.updateModelSettings({ proModels: [] });
  ai.refreshConfiguredModels();
  await assert.rejects(() => ai.runCompletion('pro', payload), /pro_model_not_configured/);
  console.log('model-runtime tests passed');
} finally {
  for (const timer of intervals) clearInterval(timer);
  await new Promise<void>(resolve => server.close(() => resolve()));
  db.close(); fs.rmSync(directory, { recursive: true, force: true });
}
